# Generated by Django 3.1.5 on 2021-08-18 05:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Descripcion del platillo', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento'),
        ),
        migrations.AlterField(
            model_name='mealclassification',
            name='img_icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Icono'),
        ),
    ]
