# Generated by Django 3.1.5 on 2021-09-05 08:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20210818_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealaddon',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Descripción', null=True),
        ),
        migrations.AlterField(
            model_name='mealclassification',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Descripción', null=True),
        ),
        migrations.AlterField(
            model_name='mealpicture',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Descripción', null=True),
        ),
    ]
