# Generated by Django 3.2.7 on 2022-01-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20210918_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='img_thumbnail',
        ),
    ]
