# Generated by Django 3.2.7 on 2022-01-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_mealaddon_stand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mealaddon',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mealclassification',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mealpicture',
            old_name='title',
            new_name='name',
        ),
    ]
