# Generated by Django 3.2.7 on 2022-02-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_auto_20220120_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
        migrations.AddField(
            model_name='mealaddon',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
        migrations.AddField(
            model_name='mealclassification',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
        migrations.AddField(
            model_name='mealpicture',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
    ]
