# Generated by Django 3.2.7 on 2022-02-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0026_auto_20220202_1459'),
        ('meals', '0010_auto_20220202_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='stand',
            field=models.ForeignKey(help_text='Restaurante al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stand_meal', to='stands.stand', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='mealaddon',
            name='stand',
            field=models.ForeignKey(help_text='Restaurante al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='stand_meal_addon', to='stands.stand', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='mealclassification',
            name='stand',
            field=models.ForeignKey(help_text='Restaurante al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='stand_meal_classification', to='stands.stand', verbose_name='Restaurante'),
        ),
    ]
