# Generated by Django 4.1.2 on 2022-10-13 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        ('common', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userschool',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.city'),
        ),
        migrations.AddField(
            model_name='userschool',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.school'),
        ),
        migrations.AddField(
            model_name='userschool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproject',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.company'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='project_skills',
            field=models.ManyToManyField(blank=True, related_name='project_skills', to='resume.skill'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userjobpromotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userjobpromotion',
            name='user_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.userjob'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.city'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.company'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='job_promotions',
            field=models.ManyToManyField(blank=True, related_name='job_promotions', to='resume.userjobpromotion'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.skillcategory'),
        ),
    ]
