# Generated by Django 4.1.2 on 2022-11-04 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjob',
            name='contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userjob',
            name='full_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userjobpromotion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.company'),
        ),
        migrations.AddField(
            model_name='userjobpromotion',
            name='contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userjobpromotion',
            name='full_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userjobpromotion',
            name='job_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
