# Generated by Django 3.1.5 on 2021-08-03 07:33

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import tinymce.models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('token', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('language', models.CharField(blank=True, choices=[('EN', 'English'), ('ES', 'Español')], default='EN', max_length=2, null=True)),
                ('newsletter', models.BooleanField(default=False)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[512, 512], upload_to=users.models.m_user_profile.picture)),
                ('promotions', models.BooleanField(default=False)),
                ('biography', tinymce.models.HTMLField(blank=True, null=True)),
                ('owner_position', models.CharField(blank=True, max_length=32, null=True, verbose_name='Puesto de Expositor')),
                ('owner_position_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descripción del puesto en Inglés')),
                ('owner_phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono de Expositor')),
                ('owner_office_phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono de oficina de Expositor')),
                ('owner_email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email de Expositor')),
                ('owner_whatsapp', models.CharField(blank=True, max_length=14, null=True, verbose_name='Whats App de Expositor')),
                ('owner_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Dirección de Expositor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('alias', models.CharField(max_length=32)),
                ('receptor_name', models.CharField(blank=True, max_length=64, null=True, validators=[common.validators.ModelValidators.name])),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[common.validators.ModelValidators.us_phone])),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, validators=[common.validators.ModelValidators.us_zip_code])),
                ('street', models.CharField(max_length=32)),
                ('ext_number', models.CharField(blank=True, max_length=5, null=True)),
                ('int_number', models.CharField(blank=True, max_length=5, null=True)),
                ('reference', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_city_address', to='common.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User address',
                'verbose_name_plural': "User address'",
            },
        ),
    ]
