# Generated by Django 3.1.5 on 2021-09-05 08:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='owner_position_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descripción del puesto'),
        ),
    ]
