# Generated by Django 3.2.7 on 2022-01-08 02:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210918_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=tinymce.models.HTMLField(blank=True, default='Biografia del expositor', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='owner_position_description',
            field=tinymce.models.HTMLField(blank=True, default='Descripción del puesto', null=True, verbose_name='Descripción del puesto'),
        ),
    ]
