# Generated by Django 3.2.7 on 2022-02-11 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20220205_1157'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0018_auto_20220205_1157'),
        ('meals', '0011_auto_20220205_1157'),
        ('real_estate', '0004_alter_realestate_stand'),
        ('vehicles', '0006_alter_vehicle_stand'),
        ('users', '0007_usercartbuyableitems_userfavoritebuyableitems_userfavoritestands_userorder_userorderbuyableitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercartbuyableitems',
            options={'verbose_name': 'Carrito de compras', 'verbose_name_plural': 'Carritos de compras'},
        ),
        migrations.AlterField(
            model_name='usercartbuyableitems',
            name='backup_user_name',
            field=models.CharField(max_length=64, verbose_name='Nombre del comprador'),
        ),
        migrations.AlterField(
            model_name='userfavoritebuyableitems',
            name='backup_user_name',
            field=models.CharField(max_length=64, verbose_name='Nombre del comprador'),
        ),
        migrations.AlterField(
            model_name='userorderbuyableitem',
            name='backup_user_name',
            field=models.CharField(max_length=64, verbose_name='Nombre del comprador'),
        ),
        migrations.AlterUniqueTogether(
            name='usercartbuyableitems',
            unique_together={('user', 'real_estate'), ('user', 'vehicle'), ('user', 'service'), ('user', 'meal'), ('user', 'product')},
        ),
    ]
