# Generated by Django 3.2.7 on 2022-02-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220211_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='reference',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Referencia del lugar'),
        ),
    ]
