# Generated by Django 3.2.12 on 2022-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Es expsitor?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Newsletter activado?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='promotions',
            field=models.BooleanField(default=False, verbose_name='Promociones activadas?'),
        ),
    ]
