# Generated by Django 3.2.12 on 2022-03-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_useraddress_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='alias',
            field=models.CharField(max_length=64),
        ),
    ]
