# Generated by Django 4.1.2 on 2022-10-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='color',
            new_name='theme_color',
        ),
    ]
