# Generated by Django 4.1.2 on 2022-10-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_color_user_theme_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='legal_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
