# Generated by Django 3.2.7 on 2022-01-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='area',
            field=models.PositiveSmallIntegerField(blank=True, default=60, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='num_of_bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de banios'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='num_of_bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de recamaras'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='num_of_parking_spots',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de cajones de estacionamiento'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='state',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('like-new', 'like-new'), ('used', 'used')], default='new', max_length=16, null=True, verbose_name='Estado del inmueble'),
        ),
    ]
