apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
      - name: {{ .Chart.Name }}-volume
        hostPath:
          path: /shared-volumes/jenkins/
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}:{{ .Values.tag }}
        imagePullPolicy: Always
        volumeMounts:
        - name: {{ .Chart.Name }}-volume
          mountPath: /var/jenkins_home
        ports:
        - containerPort: {{ .Values.service.internalPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Chart.Name }}-certificate
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.externalPort }}
