# Generated by Django 3.1.5 on 2021-09-05 08:10

import common.models.picture
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stands', '0017_auto_20210905_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[512, 512], upload_to=common.models.picture.picture)),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de productos',
            },
        ),
        migrations.CreateModel(
            name='ProductDeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[512, 512], upload_to=common.models.picture.picture)),
                ('title', models.CharField(max_length=64)),
                ('icon', models.CharField(blank=True, help_text='Ícono', max_length=32, null=True, verbose_name='Ícono')),
            ],
            options={
                'verbose_name': 'Tipo de envío',
                'verbose_name_plural': 'Tipos de envíos',
            },
        ),
        migrations.CreateModel(
            name='ProductFeatureOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Opcion de caracteristica del producto',
                'verbose_name_plural': 'Opciones de caracteristicas del producto',
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[512, 512], upload_to=common.models.picture.picture)),
            ],
            options={
                'verbose_name': 'Foto de producto',
                'verbose_name_plural': 'Fotos del producto',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=64)),
                ('options', models.ManyToManyField(blank=True, related_name='product_feature_options', to='products.ProductFeatureOption', verbose_name='Opciones de caractarísticas del producto')),
            ],
            options={
                'verbose_name': 'Caracteristica del producto',
                'verbose_name_plural': 'Caracteristicas de los productos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[1080, 1080], upload_to=common.models.picture.picture)),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('publish_on_the_wall', models.BooleanField(default=False, verbose_name='Publicar en el muro')),
                ('price', models.DecimalField(decimal_places=2, default=5, help_text='Precio del platillo', max_digits=10, verbose_name='Precio del platillo')),
                ('discount', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Descuento de 1% a 99%', null=True, verbose_name='Descuento')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio final')),
                ('brand', models.CharField(blank=True, help_text='Marca del producto', max_length=64, null=True, verbose_name='Marca')),
                ('short_description', models.CharField(blank=True, help_text='Descripción corta (90 carácteres)', max_length=90, null=True, verbose_name='Descripción corta')),
                ('unlimited_stock', models.BooleanField(default=False, verbose_name='Stock ilimitado?')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, help_text='Cantidad de producto que existe en stock', null=True, verbose_name='Cantidad de producto')),
                ('shipping_cost', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Costo de envío')),
                ('video_link', models.CharField(blank=True, help_text='Link del vídeo de youtube', max_length=512, null=True, verbose_name='Link del vídeo')),
                ('support_email', models.EmailField(blank=True, help_text='Correo electrónico de soporte', max_length=128, null=True, verbose_name='Correo de soporte')),
                ('support_info', models.CharField(blank=True, help_text='Información de soporte', max_length=256, null=True, verbose_name='Información de soporte')),
                ('support_phone', models.CharField(blank=True, help_text='Teléfono de soporte', max_length=12, null=True, verbose_name='Teléfono de soporte')),
                ('warranty_days', models.PositiveIntegerField(blank=True, default=0, help_text='Días de garantía del producto', verbose_name='Días de garantía')),
                ('times_selled', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Cantidad de veces vendido')),
                ('views', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Cantidad de veces visto')),
                ('classification', models.ForeignKey(help_text='Clasificación al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productclassification', verbose_name='Clasificación')),
                ('delivery_type', models.ManyToManyField(blank=True, help_text='Tipo de entrega', related_name='delivery_type', to='products.ProductDeliveryType', verbose_name='Tipo de entrega')),
                ('features', models.ManyToManyField(blank=True, related_name='product_features', to='products.ProductFeature', verbose_name='Caractarísticas del producto')),
                ('product_pictures', models.ManyToManyField(blank=True, help_text='Fotos del producto', related_name='product_pictures', to='products.ProductPicture', verbose_name='Fotos')),
                ('related', models.ManyToManyField(blank=True, related_name='related_products', to='products.Product', verbose_name='Productos relacionados')),
                ('stand', models.ForeignKey(help_text='Stand al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.stand', verbose_name='Stand')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
