# Generated by Django 3.1.5 on 2021-09-05 08:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Descripción', null=True),
        ),
        migrations.AlterField(
            model_name='productclassification',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Descripción', null=True),
        ),
        migrations.AlterField(
            model_name='productdeliverytype',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Descripción', null=True),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Descripción', null=True),
        ),
    ]
