# Generated by Django 3.1.5 on 2021-09-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210905_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdeliverytype',
            name='name',
            field=models.CharField(default='Tipo de envio', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdeliverytype',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
