# Generated by Django 3.1.5 on 2021-09-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210907_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpicture',
            name='product',
            field=models.ForeignKey(default=1, help_text='Producto de la promoción', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
