# Generated by Django 3.1.5 on 2021-09-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productpicture_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatureoption',
            name='feature',
            field=models.ForeignKey(default=1, help_text='Caracteristica del producto', on_delete=django.db.models.deletion.CASCADE, to='products.productfeature', verbose_name='Caracteristica del producto'),
            preserve_default=False,
        ),
    ]
