# Generated by Django 3.1.5 on 2021-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productfeatureoption_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='productfeatureoption',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
