# Generated by Django 3.1.5 on 2021-09-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210907_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='product_features', to='products.ProductFeatureOption', verbose_name='Caractarísticas del producto'),
        ),
    ]
