# Generated by Django 3.2.7 on 2022-01-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20220109_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productclassification',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productdeliverytype',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productpicture',
            old_name='title',
            new_name='name',
        ),
    ]
