# Generated by Django 3.2.7 on 2022-01-16 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0024_auto_20220115_1800'),
        ('products', '0014_auto_20220110_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpicture',
            options={'verbose_name': 'Foto del producto', 'verbose_name_plural': 'Fotos de los productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.stand', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='productclassification',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='stands.stand', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='stands.stand', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.stand', verbose_name='Empresa'),
        ),
    ]
