# Generated by Django 3.2.7 on 2022-02-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20220120_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
        migrations.AddField(
            model_name='productclassification',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
        migrations.AddField(
            model_name='productdeliverytype',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
    ]
