# Generated by Django 3.2.7 on 2022-02-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0026_auto_20220202_1459'),
        ('products', '0017_auto_20220202_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stand_product', to='stands.stand', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='productclassification',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='stand_product_classification', to='stands.stand', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='stand_product_feature', to='stands.stand', verbose_name='Empresa'),
        ),
    ]
