# Generated by Django 3.1.5 on 2021-08-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='task_name',
            field=models.CharField(max_length=256, verbose_name='Task Name'),
        ),
    ]
