# Generated by Django 3.1.5 on 2021-08-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='type',
            field=models.CharField(blank=True, choices=[('back-end', 'back-end'), ('front-end', 'front-end'), ('server', 'server'), ('ci-cd', 'ci-cd'), ('design', 'design'), ('documentation', 'documentation'), ('change', 'change'), ('improvement', 'improvement'), ('bugfix', 'bugfix'), ('integration', 'integration')], default='front-end', max_length=32, null=True),
        ),
    ]
