# Generated by Django 3.2.7 on 2021-10-21 05:23

import common.models.system
from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20210918_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('site_name', models.CharField(default='Nedii', help_text='Nombre para mostrar en la pagina principal', max_length=32, verbose_name='Nombre del sitio')),
                ('img_logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=95, size=[512, 512], upload_to=common.models.system.picture, verbose_name='Logo de Nedii')),
                ('privacy_policy', tinymce.models.HTMLField(blank=True, default='Politica de privacidad', null=True)),
                ('terms_and_conditions', tinymce.models.HTMLField(blank=True, default='Terminos y condiciones', null=True)),
                ('user_data', tinymce.models.HTMLField(blank=True, default='Datos de usuario', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
