# Generated by Django 3.2.7 on 2022-01-25 06:53

import common.models.picture
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20220120_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, default='Descripción', null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[512, 512], upload_to=common.models.picture.picture)),
                ('position', models.CharField(blank=True, choices=[('center', 'center'), ('top', 'top'), ('right', 'right'), ('bottom', 'bottom'), ('left', 'left'), ('bottom_right', 'bottom_right'), ('bottom_left', 'bottom_left')], default='center', max_length=16, null=True)),
                ('system', models.ForeignKey(help_text='Sistema al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.system', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Foto del home',
                'verbose_name_plural': 'Fotos del home',
            },
        ),
        migrations.AddField(
            model_name='system',
            name='home_pictures',
            field=models.ManyToManyField(blank=True, help_text='Fotos del home', related_name='home_pictures', to='common.HomePicture', verbose_name='Fotos del home'),
        ),
    ]
