# Generated by Django 3.2.7 on 2022-01-28 08:13

import common.models.picture
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20220124_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepicture',
            name='img_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[1920, 1920], upload_to=common.models.picture.picture),
        ),
    ]
