# Generated by Django 3.2.7 on 2022-02-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_homepicture_img_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepicture',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
    ]
