# Generated by Django 3.2.7 on 2022-02-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_homepicture_full_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='type',
            field=models.CharField(blank=True, choices=[('back-end', 'back-end'), ('front-end', 'front-end'), ('server', 'server'), ('ci-cd', 'ci-cd'), ('design', 'design'), ('documentation', 'documentation'), ('change', 'change'), ('improvement', 'improvement'), ('bugfix', 'bugfix'), ('integration', 'integration'), ('testing', 'testing')], default='front-end', max_length=32, null=True),
        ),
    ]
