# Generated by Django 3.2.12 on 2022-03-07 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_changelog_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changelog',
            old_name='type',
            new_name='task_type',
        ),
    ]
