# Generated by Django 3.2.12 on 2022-03-18 04:53

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_rename_type_changelog_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NediiPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=32, unique=True, validators=[common.validators.ModelValidators.name])),
                ('unlimited_items', models.BooleanField(default=False, verbose_name='Anuncios ilimitados?')),
                ('number_of_items', models.PositiveSmallIntegerField(blank=True, default=4, null=True, verbose_name='Numero de anuncios')),
                ('advertising_days', models.PositiveSmallIntegerField(blank=True, default=5, null=True, verbose_name='Numero de dias de publicidad')),
                ('stand_enabled', models.BooleanField(default=True, verbose_name='Stand habilitado?')),
                ('digital_card', models.BooleanField(default=True, verbose_name='Stand habilitado?')),
                ('billed_monthly', models.BooleanField(default=True, verbose_name='Cobrado mensualmente?')),
                ('exposure', models.CharField(blank=True, choices=[('basic', 'basic'), ('medium', 'medium'), ('high', 'high'), ('full', 'full')], max_length=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Precio del plan', max_digits=10, verbose_name='Precio del plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
