# Generated by Django 3.2.12 on 2022-03-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_nediiplans_digital_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='code',
        ),
    ]
