# Generated by Django 3.2.12 on 2022-04-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_remove_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sprint',
            name='price_per_hour',
            field=models.PositiveSmallIntegerField(default=300),
        ),
    ]
