# Generated by Django 3.1.5 on 2021-08-03 07:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0002_auto_20210803_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='about',
            field=tinymce.models.HTMLField(blank=True, default='Acerca del Stand', help_text='Acerca del Stand', null=True, verbose_name='Acerca del Stand'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Descripción del stand', help_text='Descripción del stand', null=True, verbose_name='Descripción del stand'),
        ),
    ]
