# Generated by Django 3.1.5 on 2021-08-03 07:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0003_auto_20210803_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='vision',
            field=tinymce.models.HTMLField(blank=True, default='Visión del Stand', help_text='Visión del Stand', null=True, verbose_name='Visión del Stand'),
        ),
    ]
