# Generated by Django 3.1.5 on 2021-08-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0004_auto_20210803_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos de esta expo', related_name='expo_groups', to='stands.Group', verbose_name='Grupos'),
        ),
    ]
