# Generated by Django 3.1.5 on 2021-08-12 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0005_expo_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='expo',
            field=models.ForeignKey(help_text='Expo al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.expo', verbose_name='Expo'),
        ),
    ]
