# Generated by Django 3.1.5 on 2021-08-13 06:52

import common.models.picture
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0007_auto_20210812_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[512, 512], upload_to=common.models.picture.picture)),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('stand', models.ForeignKey(help_text='Stand al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='stands.stand', verbose_name='Stand')),
            ],
            options={
                'verbose_name': 'Promoción de Stand',
                'verbose_name_plural': 'Promociones de Stands',
            },
        ),
        migrations.RenameField(
            model_name='standbookingquestion',
            old_name='en_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='videolink',
            old_name='en_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='standbookingquestion',
            name='es_name',
        ),
        migrations.RemoveField(
            model_name='standbookingquestionoptions',
            name='en_value',
        ),
        migrations.RemoveField(
            model_name='standbookingquestionoptions',
            name='es_value',
        ),
        migrations.RemoveField(
            model_name='surveyquestions',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='surveyquestions',
            name='es_name',
        ),
        migrations.RemoveField(
            model_name='videolink',
            name='es_name',
        ),
        migrations.AddField(
            model_name='standbookingquestionoptions',
            name='value',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='surveyquestions',
            name='name',
            field=models.CharField(default='Survery question', max_length=128, verbose_name='Nombre en inglés'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standpictures',
            name='img_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[512, 512], upload_to=common.models.picture.picture),
        ),
        migrations.DeleteModel(
            name='StandPromotions',
        ),
        migrations.AlterField(
            model_name='stand',
            name='promotions',
            field=models.ManyToManyField(blank=True, help_text='Promociones del stand', related_name='stand_promotions', to='stands.StandPromotion', verbose_name='Promociones'),
        ),
    ]
