# Generated by Django 3.1.5 on 2021-08-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0008_auto_20210813_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestions',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Pregunta de encuesta'),
        ),
        migrations.AlterField(
            model_name='videolink',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Titulo del link'),
        ),
    ]
