# Generated by Django 3.1.5 on 2021-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0010_auto_20210813_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standbookingquestionoptions',
            name='value',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Opcion a pregunta de reservacion'),
        ),
    ]
