# Generated by Django 3.1.5 on 2021-08-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0011_auto_20210813_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stand',
            old_name='survey_quetions',
            new_name='survey_questions',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='stand_booking_quiestions',
        ),
        migrations.AddField(
            model_name='stand',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='stand_ratings', to='stands.StandRating', verbose_name='Stand ratings'),
        ),
        migrations.AddField(
            model_name='stand',
            name='stand_booking_questions',
            field=models.ManyToManyField(blank=True, help_text='Formulario de reservaciones', related_name='stand_booking_questions', to='stands.StandBookingQuestion', verbose_name='Informacion de reservaciones'),
        ),
    ]
