# Generated by Django 3.1.5 on 2021-08-15 06:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stands', '0012_auto_20210815_0644'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standrating',
            unique_together={('stand', 'author')},
        ),
    ]
