# Generated by Django 3.1.5 on 2021-08-15 06:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0013_auto_20210815_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='standrating',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Comentario adicional'),
        ),
    ]
