# Generated by Django 3.1.5 on 2021-08-18 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20210818_0537'),
        ('stands', '0015_standpromotion_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standpromotion',
            name='meal',
            field=models.ForeignKey(blank=True, help_text='Platillo de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.meal', verbose_name='Platillo'),
        ),
    ]
