# Generated by Django 3.1.5 on 2021-09-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210907_0635'),
        ('stands', '0018_auto_20210905_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='standpromotion',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Producto de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto'),
        ),
    ]
