# Generated by Django 3.2.7 on 2022-01-08 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0020_auto_20210918_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='group',
            field=models.ForeignKey(help_text='Grupo al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='stands.group', verbose_name='Pabellon'),
        ),
    ]
