# Generated by Django 3.2.7 on 2022-01-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0021_alter_stand_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='meals_max_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stand',
            name='products_max_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stand',
            name='real_state_max_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stand',
            name='services_max_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stand',
            name='vehicles_max_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
