# Generated by Django 3.2.7 on 2022-02-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0025_auto_20220120_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
        migrations.AddField(
            model_name='group',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
        migrations.AddField(
            model_name='standnews',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
        migrations.AddField(
            model_name='standpictures',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
        migrations.AddField(
            model_name='standpromotion',
            name='full_size',
            field=models.BooleanField(default=True, verbose_name='Tamano completo'),
        ),
    ]
