# Generated by Django 3.2.7 on 2022-02-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_auto_20220205_1157'),
        ('services', '0004_auto_20220205_1157'),
        ('real_estate', '0004_alter_realestate_stand'),
        ('products', '0018_auto_20220205_1157'),
        ('vehicles', '0005_auto_20220202_1459'),
        ('stands', '0026_auto_20220202_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='meal',
            field=models.ManyToManyField(blank=True, help_text='Platillos destacados', related_name='highlighted_meals', to='meals.Meal', verbose_name='Platillo'),
        ),
        migrations.AddField(
            model_name='stand',
            name='product',
            field=models.ManyToManyField(blank=True, help_text='Productos destacados', related_name='highlighted_products', to='products.Product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='stand',
            name='real_estate',
            field=models.ManyToManyField(blank=True, help_text='Inmuebles destacados', related_name='highlighted_real_estates', to='real_estate.RealEstate', verbose_name='Inmueble'),
        ),
        migrations.AddField(
            model_name='stand',
            name='service',
            field=models.ManyToManyField(blank=True, help_text='Servicios destacados', related_name='highlighted_services', to='services.Service', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='stand',
            name='vehicle',
            field=models.ManyToManyField(blank=True, help_text='Vehículos destacados', related_name='highlighted_vehicles', to='vehicles.Vehicle', verbose_name='Vehículo'),
        ),
        migrations.AddField(
            model_name='standpromotion',
            name='real_estate',
            field=models.ForeignKey(blank=True, help_text='Inmueble de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_deal', to='real_estate.realestate', verbose_name='Inmueble'),
        ),
        migrations.AddField(
            model_name='standpromotion',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Servicio de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_deal', to='services.service', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='standpromotion',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehículo de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_deal', to='vehicles.vehicle', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='standpromotion',
            name='meal',
            field=models.ForeignKey(blank=True, help_text='Platillo de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_deal', to='meals.meal', verbose_name='Platillo'),
        ),
        migrations.AlterField(
            model_name='standpromotion',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Producto de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_deal', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='standpromotion',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='stand_deal', to='stands.stand', verbose_name='Empresa'),
        ),
    ]
