# Generated by Django 3.2.7 on 2022-02-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20220205_1157'),
        ('meals', '0011_auto_20220205_1157'),
        ('real_estate', '0004_alter_realestate_stand'),
        ('products', '0018_auto_20220205_1157'),
        ('vehicles', '0006_alter_vehicle_stand'),
        ('stands', '0027_auto_20220205_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='real_estate',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='service',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='stand',
            name='highlighted_meals',
            field=models.ManyToManyField(blank=True, help_text='Platillos destacados', related_name='highlighted_meals', to='meals.Meal', verbose_name='Platillos destacados'),
        ),
        migrations.AddField(
            model_name='stand',
            name='highlighted_products',
            field=models.ManyToManyField(blank=True, help_text='Productos destacados', related_name='highlighted_products', to='products.Product', verbose_name='Productos destacados'),
        ),
        migrations.AddField(
            model_name='stand',
            name='highlighted_real_estates',
            field=models.ManyToManyField(blank=True, help_text='Inmuebles destacados', related_name='highlighted_real_estates', to='real_estate.RealEstate', verbose_name='Inmuebles destacados'),
        ),
        migrations.AddField(
            model_name='stand',
            name='highlighted_services',
            field=models.ManyToManyField(blank=True, help_text='Servicios destacados', related_name='highlighted_services', to='services.Service', verbose_name='Servicios destacados'),
        ),
        migrations.AddField(
            model_name='stand',
            name='highlighted_vehicles',
            field=models.ManyToManyField(blank=True, help_text='Vehículos destacados', related_name='highlighted_vehicles', to='vehicles.Vehicle', verbose_name='Vehículos destacados'),
        ),
    ]
