# Generated by Django 3.2.12 on 2022-03-18 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_nediiplans_digital_card'),
        ('stands', '0029_stand_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.nediiplans'),
            preserve_default=False,
        ),
    ]
