# Generated by Django 3.2.7 on 2022-01-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento'),
        ),
        migrations.AlterField(
            model_name='service',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='warranty_days',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Días de garantía del servicio', verbose_name='Días de garantía'),
        ),
        migrations.AlterField(
            model_name='serviceclassification',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento'),
        ),
        migrations.AlterField(
            model_name='serviceclassification',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servicepicture',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento'),
        ),
        migrations.AlterField(
            model_name='servicepicture',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
