# Generated by Django 3.2.7 on 2022-02-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0026_auto_20220202_1459'),
        ('services', '0003_auto_20220202_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stand_service', to='stands.stand', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='serviceclassification',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='stand_service_classification', to='stands.stand', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='stand_service_feature', to='stands.stand', verbose_name='Empresa'),
        ),
    ]
