# Generated by Django 3.2.7 on 2022-01-20 04:50

import common.models.picture
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stands', '0024_auto_20220115_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, default='Descripción', null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[1080, 1080], upload_to=common.models.picture.picture)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('year', models.CharField(help_text='Anio del vehiculo', max_length=4, verbose_name='Anio del vehiculo')),
                ('doors', models.PositiveIntegerField(default=4, help_text='Numero de puertas', verbose_name='Numero de puertas')),
                ('gas', models.BooleanField(default=True, verbose_name='Gasolina')),
                ('diesel', models.BooleanField(default=False, verbose_name='Diesel')),
                ('electric', models.BooleanField(default=False, verbose_name='Electric')),
                ('automatic', models.BooleanField(default=False, verbose_name='Transmision automatica')),
                ('four_wd', models.BooleanField(default=False, verbose_name='4x4')),
                ('all_wd', models.BooleanField(default=False, verbose_name='Todo terreno')),
                ('publish_on_the_wall', models.BooleanField(default=False, verbose_name='Publicar en el muro')),
                ('price', models.DecimalField(decimal_places=2, default=5, help_text='Precio del vehiculo', max_digits=10, verbose_name='Precio del vehiculo')),
                ('discount', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Descuento de 1% a 99%', null=True, verbose_name='Descuento')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio final')),
                ('short_description', models.CharField(blank=True, help_text='Descripción corta (90 carácteres)', max_length=90, null=True, verbose_name='Descripción corta')),
                ('video_link', models.CharField(blank=True, help_text='Link del vídeo de youtube', max_length=512, null=True, verbose_name='Link del vídeo')),
                ('support_email', models.EmailField(blank=True, help_text='Correo electrónico de soporte', max_length=128, null=True, verbose_name='Correo de soporte')),
                ('support_info', models.CharField(blank=True, help_text='Información de soporte', max_length=256, null=True, verbose_name='Información de soporte')),
                ('support_phone', models.CharField(blank=True, help_text='Teléfono de soporte', max_length=12, null=True, verbose_name='Teléfono de soporte')),
                ('warranty_days', models.PositiveIntegerField(blank=True, default=0, help_text='Días de garantía del vehiculo', verbose_name='Días de garantía')),
                ('times_selled', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Cantidad de veces vendido')),
                ('views', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Cantidad de veces visto')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehicleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Caracteristica del vehiculo',
                'verbose_name_plural': 'Caracteristicas de los vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', tinymce.models.HTMLField(blank=True, default='Descripción', null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[512, 512], upload_to=common.models.picture.picture)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Marca del vehiculo',
                'verbose_name_plural': 'Marcas de los vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehiclePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, default='Descripción', null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[512, 512], upload_to=common.models.picture.picture)),
                ('stand', models.ForeignKey(help_text='Empresa al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.stand', verbose_name='Empresa')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Vehiculo')),
            ],
            options={
                'verbose_name': 'Foto del vehiculo',
                'verbose_name_plural': 'Fotos de los vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', tinymce.models.HTMLField(blank=True, default='Descripción', null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[512, 512], upload_to=common.models.picture.picture)),
                ('name', models.CharField(max_length=64)),
                ('make', models.ForeignKey(help_text='Marca del vehiculo al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclemake', verbose_name='Marca de vehiculo')),
            ],
            options={
                'verbose_name': 'Modelo del vehiculo',
                'verbose_name_plural': 'Modelos de los vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehicleClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', tinymce.models.HTMLField(blank=True, default='Descripción', null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[512, 512], upload_to=common.models.picture.picture)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('stand', models.ForeignKey(help_text='Empresa al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='stands.stand', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoría del vehiculo',
                'verbose_name_plural': 'Categorías de vehiculos',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='classification',
            field=models.ForeignKey(help_text='Clasificación al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicleclassification', verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='vehicle_features', to='vehicles.VehicleFeature', verbose_name='Caractarísticas del vehiculo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(help_text='Modelo del vehiculo al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclemodel', verbose_name='Modelo de vehiculo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related_vehicles', to='vehicles.Vehicle', verbose_name='Vehiculos relacionados'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='stands.stand', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_pictures',
            field=models.ManyToManyField(blank=True, help_text='Fotos del vehiculo', related_name='vehicle_pictures', to='vehicles.VehiclePicture', verbose_name='Fotos'),
        ),
    ]
