# Generated by Django 3.2.7 on 2022-01-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleclassification',
            name='stand',
        ),
    ]
