# Generated by Django 3.2.7 on 2022-01-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20220120_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='state',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('like-new', 'like-new'), ('used', 'used')], default='new', max_length=16, null=True, verbose_name='Estado del vehiculo'),
        ),
    ]
